os:
  - Visual Studio 2015

platform:
  - x64

configuration:
  - Debug
  - Release

matrix:
  fast_finish: true

build_script:
  - mkdir build
  - pushd .
  - cd build
  - cmake --version
  - cmake ..
  - cmake --build .
  - ctest

