# As soon as Travis updates their systems, we can use container-based approach. Until then, install CMake 3.x and new
# version of GCC manually
#sudo: false
#addons:
#  apt:
#    packages:
#    - cmake

sudo: true

language: cpp

os:
  - linux

compiler:
  - clang
  - gcc

notifications:
 email:
   on_success: change
   on_failure: always

install:
  - CMAKE_VERSION_MM=3.2
  - CMAKE_VERSION_FULL=$CMAKE_VERSION_MM.2
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
    sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
      && sudo add-apt-repository -y ppa:apokluda/boost1.53
      && sudo apt-get update -qq
      && sudo apt-get install -qq g++-4.8 libboost1.53-dev --no-install-recommends
      && sudo update-alternatives --quiet --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 40 --slave /usr/bin/g++ g++ /usr/bin/g++-4.8 --slave /usr/bin/gcov gcov /usr/bin/gcov-4.8
      && sudo update-alternatives --quiet --set gcc /usr/bin/gcc-4.8
      && wget http://www.cmake.org/files/v${CMAKE_VERSION_MM}/cmake-${CMAKE_VERSION_FULL}-Linux-x86_64.sh
      && sudo sh cmake-${CMAKE_VERSION_FULL}-Linux-x86_64.sh --prefix=/usr/local --exclude-subdir;
    fi

before_script:
  - mkdir .build
  - cd .build
  - cmake --version
  - cmake -G "Unix Makefiles" ..

script:
  - make
  - make test

